
stages:
  - validate
  - deploy

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

deploy:
  stage: deploy
  script:
    - terraform plan
    - terraform apply -auto-approve
